apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api
spec:
  selector:
    matchLabels:
      app: product-api
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: product-api
    spec:
      containers:
      - name: product-api
        image: ${REPOSITORY_TAG}
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: product-service-1

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser) 
  selector:
    app: product-api
    
  ports:
    - containerPort: 80

  type: NodePort
